# Generated by Django 4.1.4 on 2023-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdetails',
            name='financial_year',
            field=models.DateField(),
        ),
    ]
