# Generated by Django 4.1.4 on 2023-02-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_alter_taxdetails_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdetails',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='taxes.userdetails'),
        ),
    ]
