# Generated by Django 4.1.4 on 2023-02-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_taxdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='taxes.userdetails'),
        ),
    ]
