# Generated by Django 4.1.4 on 2023-02-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_userfeedback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='name',
        ),
    ]
