# Generated by Django 4.1.7 on 2023-05-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSavingsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('card_title', models.CharField(max_length=50)),
                ('card_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSlabRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(blank=True, choices=[('New Regime', 'New Regime'), ('Old Regime', 'Old Regime')], default=True, help_text='regime status new or old', max_length=20)),
                ('age_group', models.CharField(blank=True, choices=[('For All Age Groups', 'For All Age Groups'), ('Below 60', 'Below 60'), ('60 to 80', '60 to 80'), ('Above 80', 'Above 80')], default='s', help_text='Age Group of People', max_length=20)),
                ('rates', models.CharField(blank=True, choices=[('0%', 'Nil'), ('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('30%', '30%')], default='0', help_text='Tax Slab Rates', max_length=20)),
                ('slabs', models.CharField(help_text='Tax Slabs', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=40)),
                ('email', models.CharField(db_column='Email', max_length=254)),
                ('password', models.CharField(db_column='Password', max_length=20)),
                ('zipcode', models.IntegerField(db_column='Zipcode', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=200)),
                ('name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='taxes.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='TaxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=20, null=True)),
                ('age_group', models.CharField(blank=True, max_length=5, null=True)),
                ('category_emp_or_pen', models.CharField(blank=True, max_length=30, null=True)),
                ('regime', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_income', models.IntegerField(blank=True, null=True)),
                ('other_income', models.IntegerField(blank=True, null=True)),
                ('standard_deduction', models.IntegerField(blank=True, null=True)),
                ('professional_tax', models.IntegerField(blank=True, null=True)),
                ('house_rent_exemption', models.IntegerField(blank=True, null=True)),
                ('home_loan', models.IntegerField(blank=True, null=True)),
                ('deductions_u_80c', models.IntegerField(blank=True, null=True)),
                ('nps_u_80c', models.IntegerField(blank=True, null=True)),
                ('taxable_income', models.IntegerField(blank=True, null=True)),
                ('tax_on_taxable_income', models.IntegerField(blank=True, null=True)),
                ('rebate_u_87a', models.IntegerField(blank=True, null=True)),
                ('surcharge_on_tax', models.IntegerField(blank=True, null=True)),
                ('education_cess', models.IntegerField(blank=True, null=True)),
                ('total_tax', models.IntegerField(blank=True, null=True)),
                ('name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.userdetails')),
            ],
        ),
    ]
