# Generated by Django 4.1.7 on 2023-03-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimages',
            old_name='carousel_image',
            new_name='photo',
        ),
    ]
