# Generated by Django 4.1.7 on 2023-05-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_alter_taxdetails_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdetails',
            name='financial_year',
            field=models.CharField(blank=True, choices=[('2023-2022', '2023-2022'), ('2022-2021', '2022-2021'), ('2021-2020', '2021-2020')], default='s', help_text='Age Group of People', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
