# Generated by Django 4.1.7 on 2023-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_taxsavingsguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlabRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(blank=True, choices=[('n', 'New Regime'), ('o', 'Old Regime')], default=True, help_text='regime status new or old', max_length=2)),
                ('age_group', models.CharField(blank=True, choices=[('f', 'For All Age Groups'), ('s', 'Below 60'), ('e', '60 to 80'), ('a', 'Above eighty')], default='s', help_text='Age Group of People', max_length=2)),
                ('rates', models.CharField(blank=True, choices=[('0', 'Nil'), ('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('30', '30%')], default='0', help_text='Tax Slab Rates', max_length=2)),
                ('slabs', models.CharField(help_text='Tax Slabs', max_length=30)),
            ],
        ),
    ]
