# Generated by Django 4.1.7 on 2023-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_taxslabrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxslabrates',
            name='age_group',
            field=models.CharField(blank=True, choices=[('For All Age Groups', 'For All Age Groups'), ('Below 60', 'Below 60'), ('60 to 80', '60 to 80'), ('Above 80', 'Above 80')], default='s', help_text='Age Group of People', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxslabrates',
            name='rates',
            field=models.CharField(blank=True, choices=[('0%', 'Nil'), ('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('30%', '30%')], default='0', help_text='Tax Slab Rates', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxslabrates',
            name='regime',
            field=models.CharField(blank=True, choices=[('New Regime', 'New Regime'), ('Old Regime', 'Old Regime')], default=True, help_text='regime status new or old', max_length=20),
        ),
    ]
